### ISSUE TITLE
Increase compression ratio

### ISSUE THREAD

**Issue by renkei** [leafac/caxa#14]
If I use `pkg` for my project, I get an executable with a file size of 85 MB, with caxa I get an executable with a file size of 32MB. So, the caxa result looks quite good. But when I 7-zip both with maximum compression level, the caxa binary is still at 30 MB while the pkg binary is at 17 MB.

When I start the executable created with caxa to get the extracted files in the tmp folder (80 MB) and then run 7-zip over the extracted files, I get a *.7z file of 17 MB again.

It looks like the compression used internally by caxa is not as efficient as 7-zip and cannot be improved by running 7-zip again (32 MB --> 30 MB).

Is it possible to use a more aggressive compression setting during the caxa run? 17 MB vs. 30 MB is nearly 50%, the smaller file size would be helpful when you need to download the executable with a slow/limited internet connection.

**Comment by leafac** [comment]
Hi @renkei,

Thanks for the information.

We’re investigating other compression solutions over here: https://github.com/leafac/caxa/pull/7 I’ll close this issue and we can continue the conversation over there.
