### ISSUE TITLE
Takes too much space  afer few runs

### ISSUE THREAD

**Issue by kybarg** [leafac/caxa#19]

**Comment by xemle** [comment]
I guess this happens due random caxa app identifier. See PR #18 to improve that.

However the space consumption should only appear on dev machines while you are bundle and start several times your app.

The normal customer just downloads your app once

**Comment by kybarg** [comment]
@xemle Yes bundle size is ok. I meant cosumption of temporary build

**Comment by leafac** [comment]
Thanks for the suggestion, I incorporated it in caxa@2.0.0: it removes the build directory as the last step. Please let me know how it works for you. (You’re also free to delete the `caxa` directory under `require("os").tmpdir()` at any point.)
