### ISSUE TITLE
Making exclude emulate include

### ISSUE THREAD

**Issue by maxb2** [leafac/caxa#27]
For some projects it would be much easier to have an include option rather than exclude. Bigger projects tend to have a lot of files not required at runtime (see dungeon-revealer/dungeon-revealer#1115). This makes it infeasible to explicitly list every pattern to exclude. Here are my attempts to get the exclude option to emulate the include option at [maxb2/caxa-exclude-example](https://github.com/maxb2/caxa-exclude-example). N.B. some of these use GNU/Linux tools and aren't necessarily portable to other OSes.

### No excludes

`npx caxa -i . -o hello-no-exclude -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/app.js"`

Archive contents:
```
app.js
.git/
node_modules/
package.json
package-lock.json
README.md
```

### Hardcode the excludes

`npx caxa -i . -o hello-exclude-names --exclude README.md .git -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/app.js"`
```
app.js 
node_modules/
package.json
package-lock.json
```

### Trying to emulate "include"

`npx caxa -i . -o hello-exclude-glob --exclude * '!app.js' '!node_modules' '!package*' -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/app.js"`
```
app.js
.git/
node_modules/
package.json
package-lock.json
```

Bash globbing doesn't include hidden files!
```
$ echo *
app.js node_modules package.json package-lock.json README.md
```

### Explicitly exclude hidden files 

`npx caxa -i . -o hello-exclude-glob-dot --exclude * '\.*' '!app.js' '!node_modules' '!package*' -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/app.js"`
```
app.js
node_modules/
package.json
package-lock.json
```

### Use `find` to list the excludes.

`EXCLUDE=$(find . -maxdepth 1 -not -path '.' -not -name 'node_modules' -not -name 'app.js' -not -name 'package*' -exec echo {} + | sed -e 's|\./||g') && npx caxa -i . -o hello-exclude-glob-find --exclude $EXCLUDE -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/app.js"`
```
app.js
node_modules/
package.json
package-lock.json
```

**Comment by maxb2** [comment]
In [dungeon-revealer](https://github.com/dungeon-revealer/dungeon-revealer) we are actually [patching caxa](https://github.com/dungeon-revealer/dungeon-revealer/blob/master/patches/caxa%2B2.0.0.patch) to convert the exclude option to an include:

```
diff --git a/node_modules/caxa/lib/index.js b/node_modules/caxa/lib/index.js
index 50d048e..9ea4337 100644
--- a/node_modules/caxa/lib/index.js
+++ b/node_modules/caxa/lib/index.js
@@ -13,13 +13,7 @@ const archiver_1 = __importDefault(require("archiver"));
 const crypto_random_string_1 = __importDefault(require("crypto-random-string"));
 const commander_1 = __importDefault(require("commander"));
 const globby_1 = __importDefault(require("globby"));
-async function caxa({ input, output, command, force = true, exclude = [], filter = (() => {
-    const pathsToExclude = globby_1.default.sync(exclude, {
-        expandDirectories: false,
-        onlyFiles: false,
-    });
-    return (path) => !pathsToExclude.includes(path);
-})(), dedupe = true, prepareCommand, prepare = async (buildDirectory) => {
+async function caxa({ input, output, command, force = true, exclude = [], dedupe = true, prepareCommand, prepare = async (buildDirectory) => {
     if (prepareCommand === undefined)
         return;
     await execa_1.default.command(prepareCommand, { cwd: buildDirectory, shell: true });
@@ -31,7 +25,13 @@ async function caxa({ input, output, command, force = true, exclude = [], filter
     if (process_1.default.platform === "win32" && !output.endsWith(".exe"))
         throw new Error("An Windows executable must end in ‘.exe’.");
     const buildDirectory = path_1.default.join(os_1.default.tmpdir(), "caxa/builds", crypto_random_string_1.default({ length: 10, type: "alphanumeric" }).toLowerCase());
-    await fs_extra_1.default.copy(input, buildDirectory, { filter });
+    const filesToInclude = globby_1.default.sync(exclude, {
+        expandDirectories: false,
+        onlyFiles: false,
+    });
+    for (const filePath of filesToInclude) {
+        await fs_extra_1.default.copy(filePath, path_1.default.join(buildDirectory, filePath));
+    }
     if (dedupe)
         await execa_1.default("npm", ["dedupe", "--production"], { cwd: buildDirectory });
     await prepare(buildDirectory);

```

**Comment by leafac** [comment]
First, thanks for the excellent investigative work (as always!).

I’m not too keen on an includes option because it’s more prone to error. If your project structure changes then things may break in the packaged version in subtle ways. (Which brings a side-question: Do you run tests on the packaged version? I don’t…)

That said, I know that the rule isn’t “don’t run with scissors”; it’s “don’t trip.” So how about this: We enable the [`dot` flag](https://github.com/mrmlnc/fast-glob#dot), then `*` matches, for example, `.git`, and you’ll be able to say:

```
$ npx caxa -i . -o hello-exclude-glob --exclude '*' '!app.js' '!node_modules' '!package*' -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/app.js"
```

Note how I’m quoting the match-all `*`. This makes it pass through shell expansion and it’ll be handled by caxa itself. It has the side-benefit of being cross-platform.

Would that make you happy?

**Comment by leafac** [comment]
Ohhh, even better idea: I don’t change anything in caxa, because the `dot` option may be confusing for people trained in Bash who expect hidden paths to not match. And on your side you do something like `--exclude '*' '.*' '!app.js` ...`.

**Comment by maxb2** [comment]
> I’m not too keen on an includes option because it’s more prone to error. If your project structure changes then things may break in the packaged version in subtle ways. (Which brings a side-question: Do you run tests on the packaged version? I don’t…)

We occasionally do manual tests. Our Dockerfile uses stages and only copies in the runtime files to the production image. We're very aware of the structure because of it.

> If your project structure changes then things may break in the packaged version in subtle ways.

In the end, exclude/include is an advanced feature, so the responsibility of producing a working file is on the user in my opinion. caxa 100% works with the defaults, but users can tinker with the advanced features "voiding the warranty".

We had a lot of trouble understanding how to use the exclude option properly. The hardest part was figuring out the dotfiles. It really needs some documentation.

> the dot option may be confusing for people trained in Bash who expect hidden paths to not match

You're probably right. However, I've been using bash for over a decade and just learned this today :sweat_smile:  I think the main source of confusion for me was trying to combine bash expansion and globby at the same time. By the way, `!` needs to be escaped/quoted in bash otherwise you get an `event not found` error. YMMV for other shells :shrug: 

The `--exclude '*' '.*' '!<include>' ...` pattern works for our bigger project. It's simple enough that I would be satisfied to use it for the time being instead of an include option so long as it is clearly documented somewhere that it emulates include.

However, I do think that include is far more intuitive to the user than exclude. It's possible to have both options like [tsconfig#include](https://www.typescriptlang.org/tsconfig#include).

**Comment by leafac** [comment]
> Our Dockerfile uses stages and only copies in the runtime files to the production image. 

Oh, so you’re using the caxa binaries even in Docker? Since you have complete control over the container I think it’s better to use a Node.js image instead of caxa… (caxa is good for when you don’t want to use Docker, of course.)

> It really needs some documentation.

I’ll document this better then. Thanks 😃

> You're probably right. However, I've been using bash for over a decade and just learned this today 😅

😃 Fun stuff!

> I think the main source of confusion for me was trying to combine bash expansion and globby at the same time.

Yeah, it’s better to let globby handle everything and prevent Bash from expanding the globs.

> By the way, ! needs to be escaped/quoted in bash otherwise you get an event not found error. YMMV for other shells 🤷

If I remember correctly in Bash `!` means “lookup an argument from a previous command,” or something like that.

> However, I do think that include is far more intuitive to the user than exclude. If you permit me another analogy, I wouldn't try to make a recipe by first listing all the ingredients in the kitchen I don't want to use.

I like your analogies!

I think you’re saying which ingredients to use in the recipe by putting then in the countertop (the `--input` folder). Then from there you can say which ingredients to ignore.

> It's possible to have both options like tsconfig#include.

I think I’d rather emulate `.gitignore` in this one. (Or is there a `.gitinclude` that had never heard of?)

---

In general my idea here is to make it harder to do the wrong thing, while still allowing the super-advanced users (you, for example) to get what they want.

**Comment by maxb2** [comment]
> Oh, so you’re using the caxa binaries even in Docker?

No, I only meant that we copy the production files after `npm run build` into a clean node container and run from there. We know exactly which files we want to include. See this [Dockerfile](https://github.com/dungeon-revealer/dungeon-revealer/blob/b1b28919edb5fef04d79f0df4e9d16db060aa200/Dockerfile#L38-L42).

> I like your analogies!

Thanks! Cooking is my other hobby so they're always about food.

> I think you’re saying which ingredients to use in the recipe by putting then in the countertop (the --input folder). Then from there you can say which ingredients to ignore. 

So, what you're saying is to move the files you want to include to a different folder and then run `caxa` from there? I could see that working, but that is just asking the user to handle the "including" themselves on their particular shell. This is really annoying to maintain in CI environments across different OSes as you saw from our livestreams :sweat_smile: (I actually tried this on Actions a while back and ran into a bug on Macos. I'll open a new issue for it.)

> In general my idea here is to make it harder to do the wrong thing, while still allowing the super-advanced users (you, for example) to get what they want.

I agree that out-of-the-box `caxa` should just work, which it does. In my opinion, include and exclude are equally likely to create a bad binary. It just depends on which mode the user tends to think. It really is the responsibility of the user to understand their project's structure to properly use these options. I think it would be enough to give a clear warning of this in the documentation and let the user find their own way. Also, advanced users tend to get upset with projects that try to be too smart. I would prefer a tool that just does what I tell it and I deal with the consequences rather than a tool that is trying to outsmart me. I would even be happy to help with the advanced documentation/examples!

The most straightforward way I can see implementing both options is by making them mutually exclusive. So, you either use `exclude` or `include` but not both (`caxa` complains and immediately exits).

**Comment by leafac** [comment]
👍 I like the idea of having `--include` and `--exclude` being mutually exclusive. Let’s have it for caxa@2.1.0.

**Comment by leafac** [comment]
The implementation ended up not being as straightforward as I expected, so I decided to just document how to emulate `--include` with `--exclude`. Let’s say that it’s designed after `.gitignore` 😃 It’s out as part of caxa@2.1.
