### ISSUE TITLE
No such thing as `npm dedupe --production` ?

### ISSUE THREAD

**Issue by pdcastro** [leafac/caxa#29]
`caxa` v1 would run `npm prune --production` followed by `npm dedupe`:

https://github.com/leafac/caxa/blob/v1.0.0/src/index.ts#L33-L34
```
  await execa("npm", ["prune", "--production"], { cwd: appDirectory });
  await execa("npm", ["dedupe"], { cwd: appDirectory });
```

`caxa` v2 changed it to `npm dedupe --production`, which I suspect may have been an accident / mistake -- was it?

https://github.com/leafac/caxa/blob/v2.0.0/src/index.ts#L67-L68
```
  if (dedupe)
    await execa("npm", ["dedupe", "--production"], { cwd: buildDirectory });
```

I gather that `npm dedupe --production` does not print any error messages, but perhaps the `--production` flag is silently ignored? In my use case (balena CLI), `npm prune --production` makes a big difference (prunes some 200MB of dev dependencies), while `npm dedupe` (with or without `--production`) only serves to "slightly break" the `npm-shrinkwrap.json` file (which can be fixed by subsequently running `npm install`).

If the intention was to run `npm prune --production` instead of `npm dedupe --production`, then a fix would be to replace `dedupe` with `prune`, but a complication is that `caxa` v2 also introduced a new `--dedupe` flag. Renaming it `--prune` would technically be a breaking change. An alternative would be to add yet another flag, `--prune`, and separate the `prune` and `dedupe` steps as was the case in `caxa` v1.

**Comment by pdcastro** [comment]
Note: I only tested it with npm v6 (6.14.12), not npm v7.

**Comment by leafac** [comment]
Thanks for reaching out!

Hmmm, so it seems that `npm dedupe --production` only works in more recent versions of npm. What this command does is remove duplications **and** remove development dependencies. All in one command—cool stuff.

The caxa v1 way was incorrect, anyway: running `npm dedupe` would undo the work of `npm prune --production`, reinstalling the development dependencies. At least that’s what happens npm 7.10.0.

Here’s what you can do in your version of npm:

1. Use `--no-dedupe` to prevent caxa from running `npm dedupe --production`.
2. Use `--prepare-command` to run whatever commands you want from within the build directory before it’s packaged. You may use something like `--prepare-command 'npm prune --production'`, for example.

Moving forward I think that people will be updating to more recent versions of npm and this workaround seems pretty usable, so I think caxa will remain as it is and I’m closing the issue. If you disagree, please let me know! 😀

I’m looking forward to having balena CLI using caxa, please let me know how it goes and if there’s anything I can do on my side to help y’all out.

**Comment by leafac** [comment]
> which I suspect may have been an accident / mistake -- was it?

No, it wasn’t 😀 https://youtu.be/XeTPAxYsT5w
