### ISSUE TITLE
[Feature] Run minimized

### ISSUE THREAD

**Issue by hrueger** [leafac/caxa#3]
Hi,
Thanks for this great tool! It works perfektly with the `serialport` dependency 😃 

I have an idea for a cool feature (and I believe this could be implemented in the go part):
I'd like to not show the black terminal window to the user. Instead, I'd like to have a little tray icon in the taskbar which shows that the app is running. 
Maybe it could habe a context menu with `Quit` and `Show logs /  output` entries.

What do you think?

**Comment by leafac** [comment]
Hi @hrueger,

Thanks for trying out caxa, for the kind words, and for reaching out with this idea.

My first thought is that a good solution for what you mentioned would be Electron, which supports tray icons and windows for showing the logs.

Why do you think it’d be advantageous to have these features in caxa instead?

And as far as the implementation goes, I guess you’re right: it’d be implemented in the Go part. As far as I know about Go (which isn’t much), Go isn’t the best option when it comes to GUIs, but I think tray icons and a simple window showing logs would be feasible.

**Comment by hrueger** [comment]
Hi @leafac,
Using electron is a great idea. Although I use it almost daily, it didn't come to my mind to use it instead of caxa. 😅
However, it needs some boilerplate code which would be the same in multiple apps. That is why I think it would be cool to have that as a caxa feature.
In addition, if I use electron, I need to package it with electron-builder for example, to get a single binary file, and then, this is an installer. That means, the app needs to be started from the installation folder / programms menu and users can't just start it by running the dist file (like in caxa). Do you know, what I mean?

**Comment by leafac** [comment]
I get it 👍

I’ll look into this at some point…

**Comment by papb** [comment]
@hrueger Electron supports portable distributions, [at least for Windows](https://www.electron.build/configuration/nsis#portable).

**Comment by leafac** [comment]
Hi y’all,

Thanks for using caxa and for the conversation here.

I’ve been thinking about the broad strategy employed by caxa and concluded that there is a better way to solve the problem. I suppose that in this new approach running minimized would be easier to implement, but unless it’s a straightforward addition I’d consider it outside the scope 😅

It’s a different enough approach that I think it deserves a new name, and it’s part of a bigger toolset that I’m building, which I call [**Radically Straightforward · Package**](https://github.com/radically-straightforward/radically-straightforward/tree/main/package).

I’m deprecating caxa and archiving this repository. I invite you to continue the conversation in [Radically Straightforward’s issues](https://github.com/radically-straightforward/radically-straightforward/issues).

Best.
