### ISSUE TITLE
integrate rcedit for windows exe modification

### ISSUE THREAD

**Issue by si458** [leafac/caxa#34]
it would be amazing if you could integrate rcedit
it allows for modification of the windows exe, so display stuff like company name, version number, icon, etc...
the raw exe is located here - https://github.com/electron/rcedit
but they also have a nodejs module too - https://github.com/electron/node-rcedit
currently i have to run 2 seperare functions
`npm run build` to make my caxa file and then run `npm run windows` to modifiy the file to add extra info

**Comment by leafac** [comment]
Yes, that’s a great idea. I’m counting this as [a vote for custom icons](https://github.com/leafac/caxa#features-to-consider-implementing-in-the-future), and I’m closing it in favor of https://github.com/leafac/caxa/issues/10, please follow along over there 😃

How would you want this integration to work?
