### ISSUE TITLE
stub--win32--ia32 is not supported

### ISSUE THREAD

**Issue by bradjin8** [leafac/caxa#35]
How can I build an app for windows x86?

`build-err Stub not found (your operating system / architecture may be unsupported): ‘C:\Workspace\hypercore-fox-helper\node_modules\caxa\stubs\stub--win32--ia32`

**Comment by si458** [comment]
currently it only supports x64 bit windows
HOWEVER the stubs are built with go so a simple change in the build process should support x32 👍 
https://github.com/leafac/caxa/blob/20f57a96960b417bb17a5bcdabbd8fe2baed012d/package.json#L23

**Comment by leafac** [comment]
Hi y’all,

Thanks for using caxa and for the conversation here.

I’ve been thinking about the broad strategy employed by caxa and concluded that there is a better way to solve the problem. It doesn’t include binaries and stubs anymore, so the issue reported here shouldn’t apply anymore. Can you please give it a try and report back?

It’s a different enough approach that I think it deserves a new name, and it’s part of a bigger toolset that I’m building, which I call [**Radically Straightforward · Package**](https://github.com/radically-straightforward/radically-straightforward/tree/main/package).

I’m deprecating caxa and archiving this repository. I invite you to continue the conversation in [Radically Straightforward’s issues](https://github.com/radically-straightforward/radically-straightforward/issues).

Best.
