### ISSUE TITLE
Windows binary MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by maxb2** [leafac/caxa#37]
See dungeon-revealer/dungeon-revealer#1545.

Windows is periodically deleting individual files from the temporary directory that the caxa binary is extracted into.
This means that the extracted node binary tries to run in a broken project directory which throws `MODULE_NOT_FOUND` errors. The current workaround for our project is to delete the caxa temporary directory and rerun the initial extraction. This only works for us because we don't store the user data in the caxa temporary directory.

Example  error:
```
D:\DnD\Dungeon Revealer>"D:\DnD\Dungeon Revealer\dungeon-revealer-windows.exe"
node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module 'C:\Users\SCrid\AppData\Local\Temp\caxa\applications\dungeon-revealer-windows\3bn3q6shhl\0\server-build\index.js'
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:772:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
```

**Comment by n1ru4l** [comment]
This might be related to this: https://winaero.com/clear-temporary-files-automatically-windows-10/

A possible workaround would be to extract the files relative to the binary or to save locations such as the user directory 🤔

**Comment by leafac** [comment]
Hi @maxb2,

Great to have another detailed report from you.

This is a rather annoying issue. It seems like temporary directories can’t be trusted.

I don’t think we have any control over the settings mentioned by @n1ru4l, so I think that the solution may be https://github.com/leafac/caxa/issues/20. This is unfortunate, because then the user is responsible for cleaning the caxa directory as stuff accumulates in there.

> This only works for us because we don't store the user data in the caxa temporary directory.

Storing application data on the caxa temporary directory would be discouraged in any platform. Even if the operating system isn’t cleaning the temporary directory during execution, it will on reboot.

**Comment by leafac** [comment]
@saostad That’s spooky. Does the application start working and then fails with a missing path? If Windows didn’t clean files in the temporary directory, and the files are still there, then what do you think the error could be?

**Comment by maxb2** [comment]
I'm not so sure that it is a Typescript error. One of our users had the node binary missing.
https://github.com/dungeon-revealer/dungeon-revealer/issues/1545#issuecomment-962463780
```
C:\Users\dnd\dungeonrevealer\dungeon-revealer-windows-v1.16.0> .\dungeon-revealer-windows.exe
2021/11/06 09:40:42 caxa stub: Failed to run command: exec: "C:\\Users\\dnd\\AppData\\Local\\Temp/caxa/applications/dungeon-revealer-windows\\3bn3q6shhl/0/node_modules/.bin/node": file does not exist
```

**Comment by leafac** [comment]
@maxb2: Are you answering to @saostad’s issue? If so, I think these are different issues, because [this error message](https://github.com/leafac/caxa/issues/37#issuecomment-936293476) is coming from Node.js, so the node executable was found.

As to the error you reported, could it be the missing `.exe` at the end?

**Comment by maxb2** [comment]
All the errors that I'm seeing are missing files in the Windows temporary directory. The executable is extracted and runs correctly at the first run, some time passes, and a subsequent run of the executable complains that a file is missing (so far either `server-build\index.js` or `node_modules/.bin/node`). We can fix this broken state by deleting the temporary directory and doing a new extraction. So, it's not an issue with our project. The extracted directory is changing over time.

**Comment by gkinsman** [comment]
Hi there! I just came across this problem in a project. Is there a way to run a script to clean the temp folder before unpacking? I'd like to keep the single executable deploy if possible, but it looks like the temp folder isn't a very safe place!

For some extra data:
- Running an executable from different locations yields different temp folders. 
- After a reboot, each of them stopped working, with different missing files.

Would a more appropriate default be a subfolder in `%APPDATA%` or `%LOCALAPPDATA%`? e.g. 
`C:\Users\george\AppData\Roaming\MyElectronApp` 
or
`C:\Users\george\AppData\Local\MyElectronApp`
Then it would be untouched by any cleanup process.

**Comment by leafac** [comment]
@gkinsman That’s the direction we’re heading: Using the `AppData` directory instead of temporary directories. There’s some discussion about it here: https://github.com/leafac/caxa/issues/20

Would you be able to sketch a pull request?

**Comment by SrZorro** [comment]
> I'm not so sure that it is a Typescript error. One of our users had the node binary missing. [dungeon-revealer/dungeon-revealer#1545 (comment)](https://github.com/dungeon-revealer/dungeon-revealer/issues/1545#issuecomment-962463780)
> 
> ```
> C:\Users\dnd\dungeonrevealer\dungeon-revealer-windows-v1.16.0> .\dungeon-revealer-windows.exe
> 2021/11/06 09:40:42 caxa stub: Failed to run command: exec: "C:\\Users\\dnd\\AppData\\Local\\Temp/caxa/applications/dungeon-revealer-windows\\3bn3q6shhl/0/node_modules/.bin/node": file does not exist
> ```

My Windows CI failed 3 times with missing `node_modules/.bin/node` when some time pases from last usage of the CI running the exe.

As a workarround now my CI runs the exe like this: `$env:TMP="$PWD\.tmp"; .\my-binary.exe`, so it gets unpacked to the working directory inside a `.tmp` directory that its not going to get tampered by the OS cleanup policies.

There is also the workarround of removing the tmp caxa every time, but that adds the overhead of extracting each time.

**Comment by leafac** [comment]
@d4ncer Oh, that’s so weird! The operating system is cleaning the files in the temporary directory but keeping the directory structures? I didn’t know that was a thing…

You’re right, caxa is looking at the directory structure to determine if it needs to extract the project. This is so that caxa doesn’t need to know much about your project itself.

Perhaps this will be fixed by https://github.com/leafac/caxa/issues/20 ?

**Comment by d4ncer** [comment]
> @d4ncer Oh, that’s so weird! The operating system is cleaning the files in the temporary directory but keeping the directory structures? I didn’t know that was a thing…

Yeah, it's **really** odd! I'm going to now invest on the macOS side to see why this is happening. 

> You’re right, caxa is looking at the directory structure to determine if it needs to extract the project. This is so that caxa doesn’t need to know much about your project itself.

Yup, this makes total sense. 

> Perhaps this will be fixed by #20 ?

It will! Is someone driving this feature?

**Comment by leafac** [comment]
> @d4ncer 
>
> It will! Is someone driving this feature?

I don’t think anyone is working on this right now. Do you want to give it a try? 😁

**Comment by d4ncer** [comment]
> I don’t think anyone is working on this right now. Do you want to give it a try? 😁

Will give it a shot :)

**Comment by leafac** [comment]
> @d4ncer 
>
> Will give it a shot :)

Hello 👋

Did you have a chance to start working on https://github.com/leafac/caxa/issues/20 ? How’s that going?

It seems that @gkinsman is also interested in giving it a shot, so it’d be nice for us to sync our efforts…

**Comment by d4ncer** [comment]
@leafac Totally dropped the ball on this, sorry :( Glad someone else is picking it up though! Happy to help support @gkinsman or @maxb2 with testing.

**Comment by leafac** [comment]
Hi y’all,

Thanks for using caxa and for the conversation here.

I’ve been thinking about the broad strategy employed by caxa and concluded that there is a better way to solve the problem. It no longer extracts your application into a temporary directory, so it shouldn’t run into the issues we talked about here. Can you please give it a try and report back?

It’s a different enough approach that I think it deserves a new name, and it’s part of a bigger toolset that I’m building, which I call [**Radically Straightforward · Package**](https://github.com/radically-straightforward/radically-straightforward/tree/main/package).

I’m deprecating caxa and archiving this repository. I invite you to continue the conversation in [Radically Straightforward’s issues](https://github.com/radically-straightforward/radically-straightforward/issues).

Best.
