### ISSUE TITLE
Generate Linux  binary from Windows

### ISSUE THREAD

**Issue by tufik2** [leafac/caxa#39]
Hi, nice job.
I only have a question, is possible generate a Linux executable from Windows 10?

**Comment by leafac** [comment]
Hi @tufik2,

Thanks for the nice words and for reaching out.

I think that the best way to generate a Linux executable from Windows 10 is via the Windows Subsystem for Linux. In other words, you sidestep the issue by generating the Linux executable from Linux.

That said, if your project doesn’t use native extensions (things like SQLite, Sharp, and so forth), you may get away with just grabbing the Linux version of the Node executable, the Linux stub for caxa, and putting things together yourself. For more information, read this section of the documentation: https://github.com/leafac/caxa#why-no-cross-compilation-why-no-different-versions-of-nodejs-besides-the-version-with-which-caxa-was-called

Let me know how it goes.

Best.
