### ISSUE TITLE
I am so confused - how to build for Linux Arm64?

### ISSUE THREAD

**Issue by thanpolas** [leafac/caxa#42]
Hey there, apologies for my comments but I find the API of this package to be very confusing.

I do not understand the syntax at all or how to build for a specific target. 

I am on MacOS, Apple M1, trying to build for raspberry pi Arm64 arch. 

Please advise what the correct CLI syntax is.

Please help and apologies again.

**Comment by leafac** [comment]
caxa [doesn’t support cross-compilation](https://github.com/leafac/caxa#why-no-cross-compilation-why-no-different-versions-of-nodejs-besides-the-version-with-which-caxa-was-called), so you must on Linux ARM64 to compile for Linux ARM64.
