### ISSUE TITLE
{{caxa}} resolves strangely on Windows

### ISSUE THREAD

**Issue by MrGung** [leafac/caxa#45]
I am trying to get caxa working on Windows - using bb (babashka) instead of node (I think that isn't relevant here).

Creating my bundle with  
`npx caxa --input bundle --output orch.exe --no-include-node -- "{{caxa}}\bb.exe" "--config {{caxa}}\lovoonl-orch.edn"`  
I get `File does not exist: --config D:\Users\T06057A\AppData\Local\Temp/caxa/applications/orch\jwegaatqat/0\lovoonl-orch.edn`  

Note the mix of path separators! It seems `{{caxa}}` is resolved strangely on Windows...

**Comment by MrGung** [comment]
works with `"--config" "{{caxa}}\lovoonl-orch.edn"`

**Comment by leafac** [comment]
I’m glad you got it working. As you probably figured at this point, the issue was that `"--config {{caxa}}\lovoonl-orch.edn"` was interpreted as a single command-line argument. And as far as I know, the resolution of `{{caxa}}` is the same in every platform.
