### ISSUE TITLE
Source code protection

### ISSUE THREAD

**Issue by sayem314** [leafac/caxa#48]
Any chance to have this feature? `pkg` works well with this but they don't support ESM yet!

**Comment by leafac** [comment]
Check out https://github.com/leafac/caxa/issues/21

In summary: It should be doable, but it’s a bit more work than you’d expect.

Do you think you could contribute to this? I’d love to see your pull request!

**Comment by sayem314** [comment]
I don't have working experience with C++ and hence I don't think I can contribute to this. For now, I'm gonna go with obfuscating.

**Comment by leafac** [comment]
Good. It’s great that obfuscation is good enough for your case. For what it’s worth, I don’t think you’d need to know C++ to use V8 snapshots (see #21)—it’s mostly a matter of figuring out the infrastructure and how the pieces connect together. And over here in caxa things are written in TypeScript & Go. Avoided C++ precisely to lower the barrier of entry for contributors like yourself.

In any case, I’m closing this issue and we can continue to have this conversation at #21.
