### ISSUE TITLE
commander package tries to use additional flags

### ISSUE THREAD

**Issue by MichaelKorn** [leafac/caxa#5]
Maybe where is a nice trick, but I suppose the commander package is very ordinary and greedy. If I add flags for node.exe in the command, it tries to use them.

Example:
`npx caxa --directory "." --command "{{caxa}}/node_modules/.bin/node.exe" "--experimental-json-modules" "{{caxa}}/src/index.mjs" --output "caxa-test.exe"`
The Output (from commander) is:
`error: unknown option '--experimental-json-modules'`

Obviously, I'm not the first to have the problem and the behavior has probably changed several times: https://github.com/tj/commander.js/issues/922
I would like to suggest switching to yargs, which is much more sophisticated and already deals with the problem: https://github.com/yargs/yargs/blob/HEAD/docs/tricks.md#quotes

**Comment by leafac** [comment]
Ooops, yeah, you’re right—thanks for pointing it out. Switching to yargs would be fine, but regardless of what we do there, I think that the `--command` should become [variadic arguments](https://github.com/tj/commander.js#specify-the-argument-syntax). For example, you’re write:

```
npx caxa --directory "." --output "caxa-test.exe" -- "{{caxa}}/node_modules/.bin/node.exe" "--experimental-json-modules" "{{caxa}}/src/index.mjs"
```

Yeah, yargs may deal with this if you use quotes inside quotes, but it gets rather ugly. Not to mention that [quotes inside quotes got me into all sorts of trouble in some other projects](https://forum.cockos.com/showpost.php?p=2401514&postcount=13).

The downside is that this would be a breaking change, so I’d have to bump the version to 2.0.0. But I’m fine with that…

What do you think?
