### ISSUE TITLE
Static assets

### ISSUE THREAD

**Issue by sayem314** [leafac/caxa#50]
How do I include static assets like a sample `txt` file and read it?

**Comment by leafac** [comment]
All files in the directory you give as `--input` to caxa will be included in the binary. You may access such files from Node.js using relative paths, for example:

```javascript
import fs from "node:fs/promises";

console.log(
  await fs.readFile(
    new URL("./example.txt", import.meta.url),
    "utf8"
  )
);
```

This is useful for including assets such as images, fonts, CSS, and so forth in web applications.

**Comment by raiomarco** [comment]
I suggest to put something about this on the readme, i searched about this for hours until i find this

**Comment by leafac** [comment]
@raiomarco Sounds good. Please send a Pull Request with a modification to the README in a way that would have helped you out.

**Comment by raiomarco** [comment]
I will try :)

I'm not really good with writing but when i can, i will do this PR

Also thanks for the response and this really great project =D
