### ISSUE TITLE
'Cannot find module' when module names start with @ sign

### ISSUE THREAD

**Issue by kbr-gmbh** [leafac/caxa#54]
For example i have an application, that uses nestjs. 
There are many imports like this: `import { Logger } from '@nestjs/common';` with an starting @ sign in the module name. 

If i run the (caxa-) executable, then i will become the error: `Error: Cannot find module '@nestjs/common'`

I've tried this with other modules but only get this error when the module names start with @ sign?!

**Comment by kbr-gmbh** [comment]
Sorry! I've made the mistake to set the `--input` directory outside the app folder, so the executable doesn't contain the node_modules folder

**Comment by leafac** [comment]
I’m glad you figured it out. As you probably understand by now, caxa makes no distinction to modules whose names start with a `@`.
