### ISSUE TITLE
API usage in ESM module: TypeError: caxa is not a function

### ISSUE THREAD

**Issue by jeffrson** [leafac/caxa#58]
In an ESM module file, say test.mjs,

```
import caxa from 'caxa'

caxa({
    input: '.',
    output: 'out.exe',
    command: ['node', 'index.js']
})
```

caxa cannot be called: `node test.mjs` shows "TypeError: caxa is not a function".

I would assume, it's related to how
```
export default async function caxa({...
```
is handled. Maybe you find a better way to be ESM compatible.

**Comment by leafac** [comment]
Hi @jeffrson,

Thanks for reaching and for the bug report.

For the time being, you can try something like:

```typescript
import { default: caxa } from 'caxa'
```

I haven’t tested, but it may work.

The next version of caxa will be ESM-only, and this point will become moot.

**Comment by GabenGar** [comment]
`import { default: caxa }` is not a valid ESM construct. But `import {default as caxa}` doesn't work either. 
I went for:
```javascript
import caxa from 'caxa'
await caxa.default()
```
Which does work at runtime, despite what typescript thinks.

**Comment by leafac** [comment]
@jeffrson & @GabenGar: caxa starting version 3.0.0 is an [ESM-only package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). This means there’s no more awkward imports:

```typescript
import caxa from "caxa";
```

 👏
