### ISSUE TITLE
Windows executable can't be code-signed

### ISSUE THREAD

**Issue by jry2** [leafac/caxa#62]
We would like to code-sign caxa produced executable with 
`"C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x64\signtool.exe" sign /f "xxxxxx.pfx" /fd sha1 /tr http://timestamp.digicert.com/sha1/timestamp /td sha1 /p xxxxxxx  /v %*`

unfortunately we are receiving following error while starting it:
```2022/08/12 16:32:04 caxa stub: Failed to parse JSON in footer: invalid character '?' looking for beginning of value```

**Comment by leafac** [comment]
@jry2: Thanks for reaching out and for the information. This is a known limitation of caxa, and I don’t know much about the process of code-signing.

Do you know what `signtool.exe` is doing to the executable? Perhaps it’s adding some material to the end of the file, which would throw off the extraction mechanism in the caxa stub?

Do you know what it would take to solve this issue?

**Comment by dmpriso** [comment]
Yes it is adding something to the executable. I have implemented appending additional data to the executable before code-signing myself and the solution was to use a unique prefix to my custom data, which can be searched for in the whole executable (e.g. a GUID).

**Comment by leafac** [comment]
Hi @jry2,

Thanks for using caxa and for reporting this issue.

I’ve been thinking about the broad strategy employed by caxa and concluded that there is a better way to solve the problem. I wonder how it interacts with code signing 🤔 Can you please take a look and let me know?

It’s a different enough approach that I think it deserves a new name, and it’s part of a bigger toolset that I’m building, which I call [**Radically Straightforward · Package**](https://github.com/radically-straightforward/radically-straightforward/tree/main/package).

I’m deprecating caxa and archiving this repository. I invite you to continue the conversation in [Radically Straightforward’s issues](https://github.com/radically-straightforward/radically-straightforward/issues).

Best.
