### ISSUE TITLE
Freebsd stub ?

### ISSUE THREAD

**Issue by Kos-M** [leafac/caxa#65]
Hi   , nice work.
Tried to compile for a server , running freebsd--x64.
Any plans to support more archs ?
Or any guide to create devs their own stubs ?

**Comment by leafac** [comment]
Hi @Kos-M,

Thanks for reaching out.

[Here’s how we generate the stubs](https://github.com/leafac/caxa/blob/6f0a10ef252bd84a937eacb1b3067374db4d6035/package.json#L26).

I suppose it’ll be something like:

```
cross-env CGO_ENABLED=0 GOOS=freebsd GOARCH=x64 go build -o stubs/stub--freebsd--x64 stubs/stub.go && shx echo >> stubs/stub--freebsd--x64 && shx echo CAXACAXACAXA >> stubs/stub--freebsd--x64
```

Let me know how this works for you.

**Comment by Kos-M** [comment]
Thanks @leafac , currently there is no need for a build in that platform , if this will change ill check your suggestion.
