### ISSUE TITLE
Guidance to change from os.tmpDir() to arbitrary path

### ISSUE THREAD

**Issue by danielmorena** [leafac/caxa#66]
First of all, thanks for your elegant solution !
I'm reaching out because i have a specific need, which is define the path in which the app will be unpacked.
Reading the source code, i understood that i need to change de path at go stub recompile it (any guidance here or example will be excellent i didn't work with go yet), and in the .mts file in node part. That's it? or i should be aware of something else?
If there's  i way to read this info for the flags/arguments you pass to caxa itself to trigger the compilation, i'm up to implement and create a PR to the project :)

**Comment by leafac** [comment]
@danielmorena Please look at https://github.com/leafac/caxa/issues/20

Looking forward to your contribution.
