### ISSUE TITLE
Are multiple commands supported?

### ISSUE THREAD

**Issue by khan-zia** [leafac/caxa#74]
Hi, thank you for this great package. This is currently the only one that works with ESM. I was wondering if you need to run multiple commands when the executable is launched, is that possible? also, it seems that the **`--command`** parameter no longer exists which you have used in your example and video. It would be nice if this were appropriately documented in the Readme.

By multiple commands, I mean other than **`.bin/node`**. In my particular use case, I have also bundled a react front-end, of course, the built version inside the **`.exe`**. I need some sort of static file server to serve the react app on a localhost port. For this to work, I tried adding [http-server](https://github.com/http-party/http-server) which is a light static file server, and I now I need my **`.exe`** to also run a **`.bin/http-server`** command along with the node command to start the backend and also serve the frontend at the same time.

Here are two variations that I tried but they don't seem to work.

```
npx caxa --input . --output "./app.exe" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/index.js" -- "{{caxa}}/node_modules/.bin/http-server" "{{caxa}}/front-end" "-p 6971" "-d flase" "-o" "-s"

npx caxa --input . --output "./app.exe" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/index.js" "{{caxa}}/node_modules/.bin/http-server" "{{caxa}}/front-end" "-p 6971 -d flase -o -s"
```

As you can see I am trying to serve the contents of the **`front-end`** folder on port 6971 but it does not work. I took a quick look through the caxa's main source code and I see that it treats the entire input as a single command which perhaps is the issue.

**Comment by leafac** [comment]
Hi @khan-zia,

Thanks for considering using caxa. As you pointed out, caxa had a single point of entry. You could start multiple subprocesses from there. Perhaps something like [`concurrently`](https://npm.im/concurrently) would be helpful.

In any case, I’ve been thinking about the broad strategy employed by caxa and concluded that there is a better way to solve the problem.

It’s a different enough approach that I think it deserves a new name, and it’s part of a bigger toolset that I’m building, which I call [**Radically Straightforward · Package**](https://github.com/radically-straightforward/radically-straightforward/tree/main/package).

I’m deprecating caxa and archiving this repository. I invite you to continue the conversation in [Radically Straightforward’s issues](https://github.com/radically-straightforward/radically-straightforward/issues).

Best.
