### ISSUE TITLE
My code becomes exposed

### ISSUE THREAD

**Issue by AiceGate** [leafac/caxa#80]
I tried Caxa on Windows, and it's really cool. However, after a few attempts, it turns out that when Caxa is executed, it extracts all of my JavaScript to the temp folder:
C:\Users\user\AppData\Local\Temp\caxa\applications\my_app\nmyjantne4\0
and everything becomes readable.
For production, this is definitely a disadvantage as my code becomes exposed.

To prevent that, I had to obfuscate my code before building it into an executable.

**Comment by damartripamungkas** [comment]
in the README it's clear that "caxa doesn't protect your code"

**Comment by damartripamungkas** [comment]
in the README it's clear that "caxa doesn't protect your code"

> I tried Caxa on Windows, and it's really cool. However, after a few attempts, it turns out that when Caxa is executed, it extracts all of my JavaScript to the temp folder: C:\Users\user\AppData\Local\Temp\caxa\applications\my_app\nmyjantne4\0 and everything becomes readable. For production, this is definitely a disadvantage as my code becomes exposed.
> 
> To prevent that, I had to obfuscate my code before building it into an executable.

in the README it's clear that "caxa doesn't protect your code"

**Comment by damartripamungkas** [comment]
> I tried Caxa on Windows, and it's really cool. However, after a few attempts, it turns out that when Caxa is executed, it extracts all of my JavaScript to the temp folder: C:\Users\user\AppData\Local\Temp\caxa\applications\my_app\nmyjantne4\0 and everything becomes readable. For production, this is definitely a disadvantage as my code becomes exposed.
> 
> To prevent that, I had to obfuscate my code before building it into an executable.

in the README it's clear that "caxa doesn't protect your code"

**Comment by leafac** [comment]
Hi @AiceGate and @damartripamungkas,

Thanks for considering using caxa. Really, as @damartripamungkas mentioned, hiding your code has never been a goal of caxa. For that, I recommend that you look into the support for V8 Snapshots that [has been introduced in Node.js starting 18.8.0](https://nodejs.org/en/blog/release/v18.8.0).

In any case, I’ve been thinking about the broad strategy employed by caxa and concluded that there is a better way to solve the problem.

It’s a different enough approach that I think it deserves a new name, and it’s part of a bigger toolset that I’m building, which I call [**Radically Straightforward · Package**](https://github.com/radically-straightforward/radically-straightforward/tree/main/package).

I’m deprecating caxa and archiving this repository. I invite you to continue the conversation in [Radically Straightforward’s issues](https://github.com/radically-straightforward/radically-straightforward/issues).

Best.
